export enum StoreKeys {
    SAVED_PROFILES = 'SAVED_PROFILES',
    SETTINGS_TAB = 'SETTINGS_TAB',
    TEXTRACTOR_X86_PATH = 'TEXTRACTOR_X86_PATH',
    TEXTRACTOR_X64_PATH = 'TEXTRACTOR_X64_PATH',
    TEXTRACTOR_AUTORUN = 'TEXTRACTOR_AUTORUN',

    APPEARANCE_CONFIG = 'APPEARANCE_CONFIG',
}