/** @deprecated */
export const CONFIG_SOURCE_KEY = 'CONFIG_SOURCE';
export const SAVED_PROFILES_KEY = 'SAVED_PROFILES';

export enum StoreKeys {
    SAVED_PROFILES = 'SAVED_PROFILES',
    SETTINGS_TAB = 'SETTINGS_TAB',
    TEXTRACTOR_X86_PATH = 'TEXTRACTOR_X86_PATH',
    TEXTRACTOR_X64_PATH = 'TEXTRACTOR_X64_PATH'
}