import {app, BrowserWindow} from 'electron';
import makeWindowFullyDraggable from '../../utils/makeWindowFullyDraggable';
import type Store from 'electron-store';
import readStoreStateSync from '../../utils/readStoreStateSync';
import MainWindowAppearanceConfig, {
    defaultMainWindowAppearance,
    MainWindowDragMode
} from '../../configuration/appearance/MainWindowAppearanceConfig';
import {StoreKeys} from '../../constants/store-keys';
import MainWindowDragState from './logic/MainWindowDragState';
import {setVibrancy} from 'electron-acrylic-window';
import getVibrancyConfig from './utils/getVibrancyConfig';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export function createMainWindow(store: Store): BrowserWindow {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 200,
        width: 900,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
            nodeIntegration: true,
            devTools: true
        },
        transparent: true,
        frame: false,
        resizable: true,
        movable: true,
        alwaysOnTop: true
        // {
        //     theme: 'dark',
        //         effect: 'acrylic',
        //     disableOnBlur: false,
        //     useCustomWindowRefreshMethod: false,
        //     maximumRefreshRate: 165
        // }
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    mainWindow.webContents.openDevTools();

    const appearanceConfig = readStoreStateSync<MainWindowAppearanceConfig>(store, StoreKeys.SETTINGS_APPEARANCE_MAIN_WINDOW, defaultMainWindowAppearance, (appearanceConfig) => {
        // const currentVibrancy = getVibrancyConfig(appearanceConfig);
        // console.log('currentVibrancy', currentVibrancy);
        // setVibrancy(mainWindow as any, currentVibrancy);
    });
    (global as any).MainWindowDragState ??= {
        isDraggable: false
    } as typeof MainWindowDragState;

    makeWindowFullyDraggable(mainWindow, () => {
        const isFullyDraggable = appearanceConfig.current?.windowDragMode === MainWindowDragMode.ENTIRE_WINDOW;
        if (isFullyDraggable) {
            return true;
        }

        return ((global as any).MainWindowDragState as typeof MainWindowDragState)?.isDraggable;
    });

    mainWindow.on('close', () => {
        app.quit();
    });

    return mainWindow;
}